### ISSUE TITLE
yarn.lock to package-lock.json conversion ignores workspaces

### ISSUE THREAD

**Issue by qwelias** [imsnif/synp#44]
#### Issue description:
~Workspaces may have specific versions of dependencies which would not get hoisted to the root level, but synp [accounts only for root node_modules](https://github.com/imsnif/synp/blob/5ae522c2290c310275030d3a3bbb901dc999b07c/lib/index.js#L12)~ Looks like there's an issue with `nmtree`, which leads to a loss of information in resulting `package-lock.json`

[test repo](https://github.com/qwelias/yarn-audit-fix-test/blob/master/yarn.lock)

produced `package-lock.json` does not have other lodash versions:
```json
{"name":"test-yarn-audit-fix","version":"1.0.0","lockfileVersion":1,"requires":true,"dependencies":{"lodash":{"version":"3.10.1","resolved":"https://registry.yarnpkg.com/lodash/-/lodash-3.10.1.tgz","integrity":"sha1-W/Rejkm6QYnhfUgnid/RW9FAt7Y="}}}
```

UPD: fixed repo link

**Comment by antongolub** [comment]
@qwelias 
Take a look: https://github.com/imsnif/nmtree/blob/master/index.js#L25
```javascript
if (fs.existsSync(nodeModulesPath)) { // TODO: and is dir
      const nodeModulesPackages = fs.readdirSync(nodeModulesPath)
      nodeModulesPackages
      .filter(dir => !/^\./.test(dir)) // no hidden directories (eg. .bin)
      .reduce((packages, dir) => mergeScopes(nodeModulesPath, packages, dir), [])
      .forEach(nmPackage => nmTree(path.join(nodeModulesPath, nmPackage), tree))
    }
```
As I remember, `fs.readdirSync` ignores symlinks by default. But we could try running dir scanner with [`withFileTypes` option](https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options).

**Comment by antongolub** [comment]
I'll try to fix it on this weekend.

**Comment by imsnif** [comment]
Hey, @qwelias - I think now with @antongolub's fixed published we can close this, right?

**Comment by qwelias** [comment]
Hi, there's something strange. @antongolub 

If you run `synp --source-file yarn.lock` in the test repo, you'd get `Cannot read property 'pkgPath' of undefined` error.
I tried to track it and it seems like:
- it uses `lib/lockfileV2/index.js`
- `getWorkspaces` return empty array (looks like it does not understand the wildcard)
- the error is thrown at `lib/lockfileV1/tree.js#56` because empty array of workspaces produced empty object

**Comment by antongolub** [comment]
@qwelias, 
There is a small fix: https://github.com/imsnif/synp/pull/47
Patch version hasn't been released yet, so I published it under my account: [@antongolub/synp@2.0.12](https://www.npmjs.com/package/@antongolub/synp/v/2.0.12) for testing.
Could you check this out?

**Comment by qwelias** [comment]
I think it still doesn't work
<details>
  <summary>output on test repo</summary>

```
qwelias@schibmaze ~/prj/stuff/test-yarn-audit-fix master ● (1.0.0)                                                                                                        ⬡ 12.18.1 [13:15:10]
$ synp --source-file yarn.lock && cat yarn.lock package-lock.json 
Created package-lock.json
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@4.0.0:
  version "4.0.0"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.0.0.tgz#9ac43844c595e28d30108b7ba583703395922dfc"
  integrity sha1-msQ4RMWV4o0wEIt7pYNwM5WSLfw=

lodash@4.17.0:
  version "4.17.0"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.0.tgz#93f4466e5ab73e5a1f1216c34eea11535f0a8df5"
  integrity sha1-k/RGblq3PlofEhbDTuoRU18KjfU=

lodash@^3.0.0:
  version "3.10.1"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-3.10.1.tgz#5bf45e8e49ba4189e17d482789dfd15bd140b7b6"
  integrity sha1-W/Rejkm6QYnhfUgnid/RW9FAt7Y=
{
  "name": "test-yarn-audit-fix",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "test-yarn-audit-fix",
      "version": "1.0.0",
      "license": "MIT",
      "workspaces": [
        "packages/*"
      ],
      "dependencies": {
        "lodash": "^3.0.0"
      }
    },
    "node_modules/lodash": {
      "version": "3.10.1",
      "resolved": "https://registry.yarnpkg.com/lodash/-/lodash-3.10.1.tgz",
      "integrity": "sha1-W/Rejkm6QYnhfUgnid/RW9FAt7Y=",
      "license": "MIT"
    }
  },
  "dependencies": {
    "lodash": {
      "version": "3.10.1",
      "resolved": "https://registry.yarnpkg.com/lodash/-/lodash-3.10.1.tgz",
      "integrity": "sha1-W/Rejkm6QYnhfUgnid/RW9FAt7Y="
    }
  }
}%            
```
</details>

**Comment by antongolub** [comment]
Thanks for the feedback. I'll let you know when I fix this issue.

**Comment by qwelias** [comment]
Btw [test repo](https://github.com/qwelias/yarn-audit-fix-test) was linked in the initial issue comment, so you can test the implementation :)
I'd like to provide more help, but am occupied with other things until the weekend

**Comment by antongolub** [comment]
@qwelias

From v1.8.1 synp provides experimental support for workspaces. This feature could be enabled with `--with-workspaces` flag.
